string function
string key
string location
---
uint32 status 
string name
string tools
string program
string poNum
string partNumber
string partSerialNumber
string sourceName
float64 sourcePosX
float64 sourcePosY
float64 sourcePosZ
float64 sourceOrientX
float64 sourceOrientY
float64 sourceOrientZ
float64 sourceOrientW
string destName
float64 destPosX
float64 destPosY
float64 destPosZ
float64 destOrientX
float64 destOrientY
float64 destOrientZ
float64 destOrientW